const String CONST_FIRST_TIME = 'FIRST_TIME';
const String CONST_LANG_CODE = 'LANG_CODE';
const String CONST_LOGGINED = 'LOGGINED';

const String CONST_USER_ID = 'USER_ID';
const String CONST_USER_TOKEN = 'USER_TOKEN';
const String CONST_USER_REFRESHTOKEN = 'USER_REFRESHTOKEN';
